# Amira Project 630
# Amira
# Generated by Amira 6.3.0

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 5
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show
set hideNewModules 0
[ load ${SCRIPTDIR}/sample_12-files/sample_12.rec ] setLabel "sample_12.rec"
[ load ${SCRIPTDIR}/sample_12-files/sample_12.labels ] setLabel "sample_12.labels"
"sample_12.labels" ImageData connect "sample_12.rec"
