# Amira Project 201910
# Amira
# Generated by Amira 2019.1
remove -all
remove "labels.am" "blob.tiff" "blob.labels"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 5
viewer 0 setAutoRedraw 0
viewer 0 show
viewer 1 setTransparencyType 5
viewer 1 setAutoRedraw 0
viewer 1 show
viewer 2 setTransparencyType 5
viewer 2 setAutoRedraw 0
viewer 2 show
viewer 3 setTransparencyType 5
viewer 3 setAutoRedraw 0
viewer 3 show
mainWindow show

set hideNewModules 1
[ load ${SCRIPTDIR}/template-files/labels.am ] setLabel "labels.am"
"labels.am" setIconPosition 0 0
"labels.am" setNoRemoveAll 1
"labels.am" setVar "CustomHelp" {HxColormap256}
"labels.am" fire
"labels.am" setMinMax 1 8
"labels.am" flags setValue 1
"labels.am" shift setMinMax -1 1
"labels.am" shift setButtons 0
"labels.am" shift setEditButton 1
"labels.am" shift setIncrement 0.133333
"labels.am" shift setValue 0
"labels.am" shift setSubMinMax -1 1
"labels.am" scale setMinMax 0 1
"labels.am" scale setButtons 0
"labels.am" scale setEditButton 1
"labels.am" scale setIncrement 0.1
"labels.am" scale setValue 1
"labels.am" scale setSubMinMax 0 1
"labels.am" fire
"labels.am" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/template-files/blob.tiff ] setLabel "blob.tiff"
"blob.tiff" setIconPosition 20 10
"blob.tiff" sharedColormap disconnect
"blob.tiff" sharedColormap setDefaultColor 0.8 0.8 0.8
"blob.tiff" sharedColormap setDefaultAlpha 0.500000
"blob.tiff" sharedColormap activateLocalRange 1
"blob.tiff" sharedColormap setLocalMinMax 0.000000 1.000000
"blob.tiff" sharedColormap enableAlpha 1
"blob.tiff" sharedColormap enableAlphaToggle 1
"blob.tiff" sharedColormap setAutoAdjustRangeMode 1
"blob.tiff" sharedColormap setColorbarMinMax 0 321.174
"blob.tiff" fire
"blob.tiff" fire
"blob.tiff" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/template-files/blob.labels ] setLabel "blob.labels"
"blob.labels" setIconPosition 20 36
"blob.labels" sharedColormap connect "labels.am"
"blob.labels" sharedColormap setDefaultColor 0.8 0.8 0.8
"blob.labels" sharedColormap setDefaultAlpha 0.500000
"blob.labels" sharedColormap activateLocalRange 1
"blob.labels" sharedColormap setLocalMinMax 1.000000 8.000000
"blob.labels" sharedColormap enableAlpha 1
"blob.labels" sharedColormap enableAlphaToggle 1
"blob.labels" sharedColormap setAutoAdjustRangeMode 1
"blob.labels" sharedColormap setColorbarMinMax 0 120
"blob.labels" ImageData connect "blob.tiff"
"blob.labels" fire
"blob.labels" primary setIndex 0 0
"blob.labels" fire
"blob.labels" setViewerMask 49151
"blob.labels" select

set hideNewModules 0

viewer 0 setCameraOrientation 1 0 0 3.14159
viewer 0 setCameraPosition 0 2.11567e-07 -2.42005
viewer 0 setCameraFocalDistance 2.42005
viewer 0 setCameraNearDistance 1.42005
viewer 0 setCameraFarDistance 3.42005
viewer 0 setCameraType perspective
viewer 0 setCameraHeightAngle 44.9023
viewer 0 setAutoRedraw 1
viewer 0 redraw

viewer 1 setCameraOrientation 1 0 0 3.14159
viewer 1 setCameraPosition 0 -6.13526e-06 -2.42005
viewer 1 setCameraFocalDistance 2.42005
viewer 1 setCameraNearDistance 1.42005
viewer 1 setCameraFarDistance 3.42005
viewer 1 setCameraType perspective
viewer 1 setCameraHeightAngle 44.9023
viewer 1 setAutoRedraw 1
viewer 1 redraw

viewer 2 setCameraOrientation 1 0 0 3.14159
viewer 2 setCameraPosition 0 -6.13526e-06 -2.42005
viewer 2 setCameraFocalDistance 2.42005
viewer 2 setCameraNearDistance 1.42005
viewer 2 setCameraFarDistance 3.42005
viewer 2 setCameraType perspective
viewer 2 setCameraHeightAngle 44.9023
viewer 2 setAutoRedraw 1
viewer 2 redraw

viewer 3 setCameraOrientation 1 0 0 3.14159
viewer 3 setCameraPosition 0 -6.13526e-06 -2.42005
viewer 3 setCameraFocalDistance 2.42005
viewer 3 setCameraNearDistance 1.42005
viewer 3 setCameraFarDistance 3.42005
viewer 3 setCameraType perspective
viewer 3 setCameraHeightAngle 44.9023
viewer 3 setAutoRedraw 1
viewer 3 redraw

"blob.labels" sharedColormap interconnect "PermanentColormapEditor" colormap
correlationPanel closeTabs
correlationPanel setTabName 0 "Correlation 1"
correlationPanel 0 setLogScalingOnAxis 0 0
correlationPanel 0 setLogScalingOnAxis 1 0

histogramPanel closeTabs
histogramPanel setTabName 0 "Histogram 1"
histogramPanel 0 setLogScalingOnAxis 0 0
histogramPanel 0 setLogScalingOnAxis 1 1

theObjectPool setSelectionOrder blob.labels
